### ISSUE TITLE
Virus total...

### ISSUE THREAD

**Issue by Metalomeus** [HuskyDG/VMOSPro_MOD#10]
![Screenshot_20211109-204704](https://user-images.githubusercontent.com/71162300/140994697-2bb14df2-18d8-4d9f-95b4-4bb7fd00ab5d.jpg)

Is THIS safe ? Because 1.43 was clean...

**Comment by HuskyDG** [comment]
Some time anti virus software thought any modified verison of any apps is malware, so you can ignore it.
It you don't really trust me, so don't use it... Use the original VMOS Pro.

**Comment by MohammadRTX** [comment]
I have scanned your files very deeply and it has no malicious code and it is completely safe and the reason for detecting the virus is due to tampering with and modifying the program signature.
