### ISSUE TITLE
Vip mod not working

### ISSUE THREAD

**Issue by arby89** [HuskyDG/VMOSPro_MOD#12]
Latest v 1.5.2. Huawei nova 5t. It was working after install. But stop working after 2 days. 
![Screenshot_20211119_084323_com vmos pro](https://user-images.githubusercontent.com/35960549/142538146-0e6e6e58-609f-467e-9534-8014e718f491.jpg)

**Comment by arby89** [comment]
I guess its just unstable. Some time working some time not. The expiry date some time showing up. Some time doesnt. When the expiry date orange box missing, the mod will not working. Not sure why. 
![Screenshot_20211119_201344](https://user-images.githubusercontent.com/35960549/142621124-5248aa90-a2eb-445b-8e6b-d9ad9cfa11d0.jpg)

**Comment by HuskyDG** [comment]
Fixed by guanyinlite
