### ISSUE TITLE
In MIUI 12.5 alert trojan malware

### ISSUE THREAD

**Issue by log4she11** [HuskyDG/VMOSPro_MOD#16]
Version：v2.3.2 guanyinlite 

https://www.virustotal.com/gui/file/9e1b42e24e305c5b1110bbc8091986dfb72644cccef0b2a9d62e83c0839f4819
<img width="1329" alt="截屏2022-05-10 01 06 22" src="https://user-images.githubusercontent.com/6874179/167461291-47610159-3d95-49ac-be78-1179253a4cde.png">

**Comment by HuskyDG** [comment]
Just ignore it. antivirus marks tamperd apks as virus
