### ISSUE TITLE
Please add offline support

### ISSUE THREAD

**Issue by henk717** [HuskyDG/VMOSPro_MOD#3]
VMOS does not require internet and old versions like 1.0.3 can be used offline. The newer versions have the selection screen with the blue and green icon that depends on VMOS's servers and will otherwise block the app. Please remove this screen from the mod so it will always work even if the VMOS server goes offline in the future.

**Comment by HuskyDG** [comment]
Hi, Which version of app you are using?

**Comment by henk717** [comment]
I tried every apk, 1.0.3 unmodded works offline but the newer smaller apk's you modded all require internet until you are at the main menu. By removing that blue/green selection screen in the mod you can likely bypass this.

**Comment by HuskyDG** [comment]
The apk is encrypted, only part of it can be modded.
Try using good VPN to pass that screen or try new version 1.4.1 stable
