### ISSUE TITLE
Huawei P30 Pro Can't import local Rom?

### ISSUE THREAD

**Issue by sean6131** [HuskyDG/VMOSPro_MOD#6]
Hi, i cannot select the rom if using your mod apk (v1.4.2 Global BETA,v1.4.1 Global,stable v1.4.0) all tried can't

Then i go test with the official apk and it's working 

Any solution for this?

https://user-images.githubusercontent.com/59685524/135143646-7732a88f-4f55-4cf4-8391-ac2ae203141a.mp4

**Comment by HuskyDG** [comment]
You can try renaming it as `rom.zip` and put it into Download folder
Then import again

**Comment by sean6131** [comment]
> You can try renaming it as `rom.zip` and put it into Download folder Then import again

Hi it's "sdcard/download"?

If yes, still cannot


https://user-images.githubusercontent.com/59685524/135724303-b3f40a6c-7e3b-43c6-a1c4-3d5720713975.mp4
