### ISSUE TITLE
Rom not opening

### ISSUE THREAD

**Issue by androhavoc** [HuskyDG/VMOSPro_MOD#9]
![Screenshot_2021-10-09-21-43-16-008_com vmos pro](https://user-images.githubusercontent.com/43432156/136666178-ef092918-eeee-4a34-baea-76e42aad9e1b.jpg)

Why the rom is not running tried clear cache and re installing apps plz check what's wrong I am using poco X3 pro bought just yesterday and why it is not supporting my android version is 11.
 Plz acknowledge me where is error. Happening

**Comment by AndnixSH** [comment]
Does the other custom ROMs work?
Also if you are already using VMOS mod apk, then you don't need custom ROMs anymore. You can use official rom and root

**Comment by MohammadRTX** [comment]
Install new mod version fixed Problem
